# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ent_Assoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ent_assoc',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Graph'),
        ),
        migrations.AddField(
            model_name='ent_assoc',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Options'),
        ),
    ]
